spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:postgresql://postgresql.postgresql.svc.cluster.local:5432/postgres?currentSchema=restaurant&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  sql:
    init:
      mode: never

server:
  port: 8183

logging:
  level:
    com.food.ordering.system: INFO

kafka-config:
  bootstrap-servers: kafka-kafka-bootstrap.kafka.svc.cluster.local:9092
  schema-registry-url: http://schema-registry.kafka.svc.cluster.local:8081
