server:
  port: ${CUSTOMER_SERVICE_PORT}

customer-service:
  customer-topic-name: customer

spring:
  jpa:
    open-in-view: false
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    platform: postgres
  sql:
    init:
      mode: ${SQL_INIT_MODE}
      schema-locations: classpath:init-schema.sql

kafka-config:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  schema-registry-url-key: schema.registry.url
  schema-registry-url: ${SCHEMA_REGISTRY_URL}
  num-of-partitions: 3
  replication-factor: 3

kafka-producer-config:
  key-serializer-class: org.apache.kafka.common.serialization.StringSerializer
  value-serializer-class: io.confluent.kafka.serializers.KafkaAvroSerializer
  compression-type: snappy
  acks: all
  batch-size: 16384
  batch-size-boost-factor: 100
  linger-ms: 5
  request-timeout-ms: 60000
  retry-count: 5

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
  api-docs:
    path: /v3/api-docs