apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker-3
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker-3
  template:
    metadata:
      labels:
        app: kafka-broker-3
    spec:
      containers:
        - name: kafka-broker-3
          image: confluentinc/cp-kafka:7.7.0
          ports:
            - containerPort: 9092
            - containerPort: 9093
          env:
            - name: KAFKA_NODE_ID
              value: "3"
            - name: CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  name: kafka-cluster-id
                  key: clusterId
            - name: KAFKA_LISTENERS
              value: BROKER://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
            - name: KAFKA_ADVERTISED_LISTENERS
              value: BROKER://kafka-broker-3:9092
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: BROKER
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: CONTROLLER
            - name: KAFKA_COMPRESSION_TYPE
              value: producer
            - name: KAFKA_PROCESS_ROLES
              value: controller,broker
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: 1@kafka-broker-1:9093,2@kafka-broker-2:9093,3@kafka-broker-3:9093
            - name: KAFKA_LOG_DIRS
              value: /tmp/kraft-logs
            - name: KAFKA_LOG_SEGMENT_BYTES
              value: "16384"
          command:
            - /bin/bash
            - -c
            - |
              export KAFKA_KRAFT_MODE=true
              export CLUSTER_ID=$CLUSTER_ID
              echo "kafka.properties oluşturuluyor..."
              /etc/confluent/docker/configure
              kafka-storage format --ignore-formatted -t $CLUSTER_ID -c /etc/kafka/kafka.properties
              /etc/confluent/docker/run
          volumeMounts:
            - name: kafka-logs
              mountPath: /tmp/kraft-logs
      volumes:
        - name: kafka-logs
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-3
  namespace: development
spec:
  selector:
    app: kafka-broker-3
  ports:
    - name: broker
      port: 9092
      targetPort: 9092
    - name: controller
      port: 9093
      targetPort: 9093