apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-init-topics
  namespace: development
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: init-kafka
          image: confluentinc/cp-kafka:7.7.0
          command:
            - /bin/sh
            - -c
            - |
              kafka-topics --bootstrap-server kafka-broker-1:9092 --list
              
              kafka-topics --bootstrap-server kafka-broker-1:9092 --topic payment-request --delete --if-exists
              kafka-topics --bootstrap-server kafka-broker-1:9092 --topic payment-response --delete --if-exists
              kafka-topics --bootstrap-server kafka-broker-1:9092 --topic restaurant-approval-request --delete --if-exists
              kafka-topics --bootstrap-server kafka-broker-1:9092 --topic restaurant-approval-response --delete --if-exists
              kafka-topics --bootstrap-server kafka-broker-1:9092 --topic customer --delete --if-exists
              
              kafka-topics --bootstrap-server kafka-broker-1:9092 --create --if-not-exists --topic payment-request --replication-factor 3 --partitions 3
              kafka-topics --bootstrap-server kafka-broker-1:9092 --create --if-not-exists --topic payment-response --replication-factor 3 --partitions 3
              kafka-topics --bootstrap-server kafka-broker-1:9092 --create --if-not-exists --topic restaurant-approval-request --replication-factor 3 --partitions 3
              kafka-topics --bootstrap-server kafka-broker-1:9092 --create --if-not-exists --topic restaurant-approval-response --replication-factor 3 --partitions 3
              kafka-topics --bootstrap-server kafka-broker-1:9092 --create --if-not-exists --topic customer --replication-factor 3 --partitions 3
              
              echo "Topics created successfully!"
              kafka-topics --bootstrap-server kafka-broker-1:9092 --list